<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H6V4GD0" failures="1" tests="3" name="Test" time="39.307" errors="0" timestamp="2024-05-16T20:43:34 IST">
  <testcase classname="com.standalone.SauceInvalidLoginTest" name="invalidLoginTest" time="2.204">
    <failure type="java.lang.AssertionError" message="Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.dsd] but found [Epic sadface: Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.dsd] but found [Epic sadface: Sorry, this user has been locked out.]
at com.standalone.SauceInvalidLoginTest.invalidLoginTest(SauceInvalidLoginTest.java:16)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest -->
  <testcase classname="com.standalone.SauceE2eTest" name="sauceE2eTest" time="18.394"/>
  <testcase classname="com.standalone.SauceDemoE2eTest" name="sauceE2eTest" time="31.978"/>
</testsuite> <!-- Test -->
