<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H6V4GD0" failures="1" tests="1" name="Test" time="7.442" errors="0" timestamp="2024-05-20T20:24:34 IST">
  <testcase classname="com.tests.SauceInvalidLoginTest" name="invalidLoginTest" time="2.576">
    <failure type="java.lang.AssertionError" message="Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.XYZ] but found [Epic sadface: Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.XYZ] but found [Epic sadface: Sorry, this user has been locked out.]
at com.tests.SauceInvalidLoginTest.invalidLoginTest(SauceInvalidLoginTest.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest -->
</testsuite> <!-- Test -->
